version: "3.4"

services:
  cakes_web:
    container_name: cakes_web
    image: cakesweb
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Cakes.Web/Dockerfile
    ports:
      - 8080:80
  cakes_api:
    container_name: cakes_api
    image: cakesapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Cakes.Api/Dockerfile
    ports:
      - 8082:80
  cakes_data:
    container_name: cakes_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: welcome1
  cakes_data_admin:
    container_name: cakes_db_admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: welcome1
      ME_CONFIG_MONGODB_SERVER: cakes_db